<a href="https://colab.research.google.com/github/shreyapriya97/ML_OPS/blob/Rutuja_mlops/SentimentAnalysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd


In [ ]:
from transformers import pipeline
help(pipeline)

Help on function pipeline in module transformers.pipelines:

pipeline(task: Optional[str] = None, model: Union[str, ForwardRef('PreTrainedModel'), ForwardRef('TFPreTrainedModel'), NoneType] = None, config: Union[str, transformers.configuration_utils.PretrainedConfig, NoneType] = None, tokenizer: Union[str, transformers.tokenization_utils.PreTrainedTokenizer, ForwardRef('PreTrainedTokenizerFast'), NoneType] = None, feature_extractor: Union[str, ForwardRef('SequenceFeatureExtractor'), NoneType] = None, image_processor: Union[str, transformers.image_processing_utils.BaseImageProcessor, NoneType] = None, processor: Union[str, transformers.processing_utils.ProcessorMixin, NoneType] = None, framework: Optional[str] = None, revision: Optional[str] = None, use_fast: bool = True, token: Union[str, bool, NoneType] = None, device: Union[int, str, ForwardRef('torch.device'), NoneType] = None, device_map=None, torch_dtype=None, trust_remote_code: Optional[bool] = None, model_kwargs: Optional[Dict[s

Instantiate pipeline

In [ ]:
sa_pipeline=pipeline("sentiment-analysis")

sa_pipeline

No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision 714eb0f (https://huggingface.co/distilbert/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.


config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

Device set to use cpu


In [ ]:
sa_pipeline=pipeline("text-classification")

sa_pipeline

No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision 714eb0f (https://huggingface.co/distilbert/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.
Device set to use cpu


In [ ]:
sa_pipeline("The sun is shining,and the birds are signing - what a beautiful day!")

[{'label': 'POSITIVE', 'score': 0.9998389482498169}]

In [ ]:
sa_pipeline("I had a flat tyre on my way to work today, and it completely ruined my morning.")

[{'label': 'NEGATIVE', 'score': 0.9997641444206238}]

In [ ]:
sa_pipeline("Today was a typical Monday - nothing extraordinary happened.")

[{'label': 'NEGATIVE', 'score': 0.9989293217658997}]

In [ ]:
sa_pipeline("I finished a book I'd been reading and it left me with mixed emotions")

[{'label': 'NEGATIVE', 'score': 0.9983609318733215}]

In [ ]:
sa_pipeline([
    "Dealing with the unexpected challenges can be quite frustrating,especially when everything seems to go wrong at once.",
    "I received a surprise gift from a friend today, and it made my whole week.",
    "Meeting new people and making meaningful connections always brings a smile to my face."
])

[{'label': 'NEGATIVE', 'score': 0.9984360337257385},
 {'label': 'POSITIVE', 'score': 0.9998192191123962},
 {'label': 'POSITIVE', 'score': 0.9998735189437866}]

In [ ]:
print(sa_pipeline.model.config.id2label)

{0: 'NEGATIVE', 1: 'POSITIVE'}


In [ ]:
import tensorflow as tf

from transformers import DistilBertTokenizer, TFAutoModelForSequenceClassification

In [ ]:
tokenizer=DistilBertTokenizer.from_pretrained("distilbert-base-uncased-finetuned-sst-2-english")

tokenizer

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

DistilBertTokenizer(name_or_path='distilbert-base-uncased-finetuned-sst-2-english', vocab_size=30522, model_max_length=512, is_fast=False, padding_side='right', truncation_side='right', special_tokens={'unk_token': '[UNK]', 'sep_token': '[SEP]', 'pad_token': '[PAD]', 'cls_token': '[CLS]', 'mask_token': '[MASK]'}, clean_up_tokenization_spaces=True, added_tokens_decoder={
	0: AddedToken("[PAD]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	100: AddedToken("[UNK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	101: AddedToken("[CLS]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	102: AddedToken("[SEP]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	103: AddedToken("[MASK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
}
)

In [ ]:
model=TFAutoModelForSequenceClassification.from_pretrained("distilbert-base-uncased-finetuned-sst-2-english")

model

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

All PyTorch model weights were used when initializing TFDistilBertForSequenceClassification.

All the weights of TFDistilBertForSequenceClassification were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFDistilBertForSequenceClassification for predictions without further training.


In [ ]:
inputs=tokenizer("I'd definitely like to do that again",return_tensors='tf')

inputs

{'input_ids': <tf.Tensor: shape=(1, 11), dtype=int32, numpy=
array([[ 101, 1045, 1005, 1040, 5791, 2066, 2000, 2079, 2008, 2153,  102]],
      dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(1, 11), dtype=int32, numpy=array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int32)>}

In [ ]:
logits=model(**inputs).logits

logits

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[-4.092141 ,  4.3566947]], dtype=float32)>

In [ ]:
predicted_class_id = int(tf.math.argmax(logits, axis=-1)[0])


can run the logits output through tf.math.argmax

In [ ]:
model.config.id2label[predicted_class_id]

'POSITIVE'

In [ ]:
inputs=tokenizer('i would not recommend that restauratn',return_tensors='tf')

inputs

{'input_ids': <tf.Tensor: shape=(1, 11), dtype=int32, numpy=
array([[  101,  1045,  2052,  2025, 16755,  2008,  2717, 21159,  4017,
         2078,   102]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(1, 11), dtype=int32, numpy=array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int32)>}

In [ ]:
logits=model(**inputs).logits

logits



<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[ 2.7573776, -2.3347328]], dtype=float32)>

In [ ]:
predicted_class_id = int(tf.math.argmax(logits, axis=-1)[0])
predicted_class_id

model.config.id2label[predicted_class_id]

'NEGATIVE'